package com.example.vitruvianredux.cloud

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

/**
 * Data Transfer Objects for Supabase Postgrest tables.
 *
 * Naming convention: `Remote<Entity>` — flat rows that map 1:1 to Supabase
 * table columns.  JSON items (e.g. program items, exercise sets) are stored
 * as serialized JSONB columns.
 *
 * Every mutable table has:
 *   - `user_id`   (UUID, injected by RLS default)
 *   - `device_id` (text, originating device)
 *   - `updated_at` (bigint epoch millis, LWW clock)
 *   - `deleted_at` (bigint nullable, soft-delete marker)
 */

// ═══════════════════════════════════════════════════════════════════════════════
//  profiles
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteProfile(
    @EncodeDefault(EncodeDefault.Mode.NEVER)
    val id: String? = null,            // UUID PK, generated by DB on insert
    @SerialName("user_id")
    val userId: String,
    @SerialName("display_name")
    val displayName: String? = null,
    @SerialName("created_at")
    val createdAt: Long = System.currentTimeMillis(),
    @SerialName("updated_at")
    val updatedAt: Long = System.currentTimeMillis(),
)

// ═══════════════════════════════════════════════════════════════════════════════
//  devices
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteDevice(
    val id: String? = null,
    @SerialName("user_id")
    val userId: String,
    @SerialName("device_id")
    val deviceId: String,
    @SerialName("device_name")
    val deviceName: String = "",
    val platform: String = "android",
    @SerialName("app_version")
    val appVersion: String = "",
    @SerialName("last_sync_at")
    val lastSyncAt: Long? = null,
    @SerialName("created_at")
    val createdAt: Long = System.currentTimeMillis(),
)

// ═══════════════════════════════════════════════════════════════════════════════
//  programs
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteProgram(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    val name: String,
    @SerialName("exercise_count")
    val exerciseCount: Int = 0,
    /** JSON-encoded List<ProgramItemDraft> */
    val items: JsonElement = JsonArray(emptyList()),
    @SerialName("sort_order")
    val sortOrder: Int = 0,
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
    @SerialName("deleted_at")
    val deletedAt: Long? = null,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  sessions  (WorkoutSessionRecord cloud copy)
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteSession(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    @SerialName("program_id")
    val programId: String? = null,
    val name: String = "",
    @SerialName("started_at")
    val startedAt: Long = 0L,
    @SerialName("ended_at")
    val endedAt: Long = 0L,
    @SerialName("total_reps")
    val totalReps: Int = 0,
    @SerialName("total_sets")
    val totalSets: Int = 0,
    @SerialName("total_volume_kg")
    val totalVolumeKg: Float = 0f,
    @SerialName("duration_sec")
    val durationSec: Int = 0,
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
    @SerialName("deleted_at")
    val deletedAt: Long? = null,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  analytics  (SessionLog cloud copy)
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteAnalyticsLog(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    @SerialName("start_time_ms")
    val startTimeMs: Long = 0L,
    @SerialName("end_time_ms")
    val endTimeMs: Long = 0L,
    @SerialName("duration_sec")
    val durationSec: Int = 0,
    @SerialName("program_name")
    val programName: String? = null,
    @SerialName("day_name")
    val dayName: String? = null,
    @SerialName("exercise_names")
    val exerciseNames: JsonElement = JsonArray(emptyList()),
    @SerialName("total_sets")
    val totalSets: Int = 0,
    @SerialName("total_reps")
    val totalReps: Int = 0,
    @SerialName("total_volume_kg")
    val totalVolumeKg: Double = 0.0,
    @SerialName("volume_available")
    val volumeAvailable: Boolean = true,
    @SerialName("heaviest_lift_lb")
    val heaviestLiftLb: Int = 0,
    val calories: Int = 0,
    @SerialName("created_at")
    val createdAt: Long = 0L,
    /** JSON-encoded List<ExerciseSetLog> */
    @SerialName("exercise_sets")
    val exerciseSets: JsonElement = JsonArray(emptyList()),
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  custom_exercises
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteCustomExercise(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    val name: String,
    @SerialName("primary_muscle_group")
    val primaryMuscleGroup: String = "",
    @SerialName("secondary_muscle_group")
    val secondaryMuscleGroup: String = "",
    @SerialName("default_tracking_type")
    val defaultTrackingType: String = "REPS",
    @SerialName("default_mode")
    val defaultMode: String? = null,
    val notes: String = "",
    @SerialName("per_side")
    val perSide: Boolean = false,
    @SerialName("is_favorite")
    val isFavorite: Boolean = false,
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
    @SerialName("deleted_at")
    val deletedAt: Long? = null,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  user_settings  (single row per user, JSON blob)
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteUserSettings(
    @SerialName("user_id")
    val userId: String,
    @SerialName("unit_system")
    val unitSystem: String = "IMPERIAL_LB",
    @SerialName("theme_mode")
    val themeMode: String = "SYSTEM",
    /** JSON-encoded JustLiftDefaults */
    @SerialName("just_lift_defaults")
    val justLiftDefaults: JsonElement = JsonObject(emptyMap()),
    /** JSON-encoded LedColorStore.ColorScheme */
    @SerialName("led_colors")
    val ledColors: JsonElement = JsonObject(emptyMap()),
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  exercise_history  (completed exercise aggregate per session)
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteExerciseHistory(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("exercise_name")
    val exerciseName: String,
    @SerialName("set_count")
    val setCount: Int = 0,
    @SerialName("total_reps")
    val totalReps: Int = 0,
    @SerialName("total_volume_kg")
    val totalVolumeKg: Float = 0f,
    @SerialName("heaviest_weight_lb")
    val heaviestWeightLb: Int = 0,
    @SerialName("completed_at")
    val completedAt: Long = 0L,
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
)

// ═══════════════════════════════════════════════════════════════════════════════
//  set_history  (completed set within an exercise)
// ═══════════════════════════════════════════════════════════════════════════════

@Serializable
data class RemoteSetHistory(
    val id: String,
    @SerialName("user_id")
    val userId: String,
    @SerialName("exercise_history_id")
    val exerciseHistoryId: String,
    @SerialName("session_id")
    val sessionId: String,
    @SerialName("exercise_name")
    val exerciseName: String,
    @SerialName("set_index")
    val setIndex: Int = 0,
    val reps: Int = 0,
    @SerialName("weight_lb")
    val weightLb: Int = 0,
    @SerialName("volume_kg")
    val volumeKg: Float = 0f,
    @SerialName("duration_sec")
    val durationSec: Int = 0,
    @SerialName("completed_at")
    val completedAt: Long = 0L,
    @SerialName("device_id")
    val deviceId: String = "",
    @SerialName("updated_at")
    val updatedAt: Long = 0L,
)
